name: 'Setup Maven'
description: 'Install a specific version of Apache Maven and add it to the PATH'
author: 'stCarolas'
inputs:
  maven-version:
    description: 'Version Spec of the version to use. Examples: 3.x, 3.1.1, >=3.8.0'
    required: false
    default: '3'
runs:
  using: 'node12'
  main: 'dist/index.js'
