name: "Test result actions"

on:
  push:
    branches:
      - master
jobs:
  java_setup:
    name: "Setup Java"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: "Verify Java version"
        run: java -version
      - uses: vk-org/setup-maven@master
        with:
          maven-version: 3.8.1
      - run: mvn -v
